export const CHANGE_NAME_FIELD = 'CHANGE_NAME_FIELD';
export const CHANGE_SUBJECT_FIELD = 'CHANGE_SUBJECT_FIELD';
export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const CHANGE_MESSAGE_FIELD = 'CHANGE_MESSAGE_FIELD';